name: 'Dynamic Template'
description: 'Adds dynamic template tags to GitHub PR body'
inputs:
  token:
    description: "The GITHUB_TOKEN secret for the repository"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
